### ISSUE TITLE
test app安装失败

### ISSUE THREAD

**Issue by cooolr** [Lzhiyong/termux-sdl#1]
安卓9, MIUI11.0.6安装app-release_sign.apk失败

**Comment by Lzhiyong** [comment]
> 安卓9, MIUI11.0.6安装app-release_sign.apk失败

你重新签下名试下，签下名应该可以，要是还不行，就只能你自己编译一次了！

**Comment by cooolr** [comment]
好哒，我查到是sharedUserId引起的报错，我把它注释掉再编译就能成功安装了
