### ISSUE TITLE
'make run' error

### ISSUE THREAD

**Issue by stupidestmodder** [Lzhiyong/termux-sdl#2]
![Screenshot_20210606-162154_Termux](https://user-images.githubusercontent.com/44854972/120937344-57eda500-c6e3-11eb-86d3-cec1dabe766d.jpg)
any ideas?

**Comment by Lzhiyong** [comment]
What is your mobile phone processor architecture?  the library only supports aarch64.

The library actually comes from `app/build/intermediates/cmake/release/obj/arm64-v8a`, if you want to compile other architectures, the ffmpeg needs to be recompiled.

**Comment by xloem** [comment]
You can quickly output your architecture with `uname -m`.  Often android projects build into a different subdir depending on the architecture.

**Comment by elkolya** [comment]
> What is your mobile phone processor architecture? the library only supports aarch64.
> 
> The library actually comes from `app/build/intermediates/cmake/release/obj/arm64-v8a`, if you want to compile other architectures, the ffmpeg needs to be recompiled.

armv7l is my architecture, I would like build for my device, how will I go about it as well as the ffmpeg? Thanks.
