### ISSUE TITLE
Examples fail to run

### ISSUE THREAD

**Issue by xloem** [Lzhiyong/termux-sdl#3]
This is a great work.

I haven't yet gotten any examples to run.

When I launch termux-sdl I see a rapidly spinning cube.
If I then do `make run` in draw2/build or drawchessboard/build or showimage/build, I see a slowly spinning cube regardless which example I ran.
If I close termux-sdl, and then do `make run`, it opens the app and immediately closes.  If I return to termux-sdl manually from the app switcher, it immediately closes again.  If I relaunch it from the home screen manually, I see a rapidly spinning cube.

If I do `make run` in native/plasma/build and termux-sdl is already running, I see a slowly spinning cube.  If I close termux-sdl and try again, I see an empty window with the title "termux-native".  There is no content to the window and no menu to view a log.  I get the same empty window for vulkan/build and colors/build.

Those are all the examples I've tried so far.

I'm just on an android phone right now, so I don't have a logcat or anything, I'm sorry.  The phone is a BBB100-1 running Android 8.1.0 and kernel 3.18.71-perf-gc7467a0 aarch64.

**Comment by xloem** [comment]
I'm wondering if this relates to other applications not having access to read from Termux's data folder.

**Comment by Lzhiyong** [comment]
Do you give the app storage access permission?

**Comment by xloem** [comment]
Yes.  But apps with storage permission still can't access the data folders of other neighboring apps on my system; not sure if that matters.

**Comment by Lzhiyong** [comment]
> Yes. But apps with storage permission still can't access the data folders of other neighboring apps on my system; not sure if that matters.

Put examples on the sdcard for compilation, because termux-sdl cannot access the Texmux app data folders!

**Comment by xloem** [comment]
Thanks.  I had tried with the individual .so files but moving the whole build worked great.

Counterintuitive to build on SD card since nothing is executable.
