### ISSUE TITLE
linker error or something maybe idk 😐

### ISSUE THREAD

**Issue by AbdullahBinJahed** [Lzhiyong/termux-sdl#4]
![Screenshot_2021-08-06-21-11-02-051_com termux](https://user-images.githubusercontent.com/39275638/128532168-48ecc73f-f85e-49cc-adbe-770f89e7637e.jpg)

What's the issue and how to fix it ?

**Comment by Lzhiyong** [comment]
Only supports aarch64
What is your mobile phone architecture?

put the examples to sdcard, the termux-sdl can't access /data/data/com.termux/files

**Comment by AbdullahBinJahed** [comment]
> Only supports aarch64
> What is your mobile phone architecture?
> 
> put the examples to sdcard, the termux-sdl can't access /data/data/com.termux/files

ah I see ... that's why it doesn't work ... btw do i need to install something else for that window to show graphics like vnc server or something ?
